version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development

version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
    command: >
      sh -c "bundle exec rails db:create &&
             bundle exec rails db:migrate &&
             bundle exec rails webpacker:compile &&
             bundle exec rails s -p 3000 -b '0.0.0.0'"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development

version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
  db:
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3035:3035"
    depends_on:
      - db

volumes:
  bundle:
  postgres:
  node_modules:

webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/favorite_spot
    ports:
      - "8000:8000"